version: '3'
services:

  address-server:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./address-server:/app
    env_file:
      - "./.env.dev"
    environment:
      - LOG_LEVEL_DEFAULT=debug
      - PORT=5007
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "5007:5007"
    command: /bin/sh -c "npm install && npm run start"

  #client:
  #  image: node:14-alpine
  #  working_dir: /app
  #  volumes:
  #    - /app/node_module
  #    - ./client:/app
  #  environment:
  #    - WSD_SOCKET_PORT=0
  #  ports:
  #    - "3000:3000"

  company-server:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./company-server:/app
    env_file:
      - "./.env.dev"
    environment:
      - LOG_LEVEL_DEFAULT=debug
      - PORT=5008
    ports:
      - "5008:5008"
    command: /bin/sh -c "npm install && npm run start"

  person-server:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./person-server:/app
    env_file:
      - "./.env.dev"
    environment:
      - LOG_LEVEL_DEFAULT=debug
      - PORT=5005
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
      - "5005:5005"
    depends_on:
      - postgres
    command: /bin/sh -c "npm install && npm run start"

  pour-server:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./pour-server:/app
    env_file:
      - "./.env.dev"
    environment:
      - LOG_LEVEL_DEFAULT=debug
      - PORT=5006
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - JSONPLACEHOLDER_API_BASE_URL=https://jsonplaceholder.typicode.com
      - LOGSTASH_ENDPOINT=http://logstash:8080
    ports:
      - "5006:5006"
    depends_on:
      - postgres
    command: /bin/sh -c "npm install && npm run start"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_PASSWORD=
      - ES_USERNAME=
      - ES_INDEX=company
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /tmp/logstash/queue:/usr/share/logstash/data/queue

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5.0
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"

volumes:
  elasticsearch-data:
