const {Pool} = require('pg');
const {PGUSER, PGHOST, PGDATABASE, PGPASSWORD, PGPORT} = require("../utils/config");
const logger = require("../utils/logger");

class DatabaseService {
  constructor() {
    this.pgClient = new Pool({
      user: PGUSER,
      host: PGHOST,
      database: PGDATABASE,
      password: PGPASSWORD,
      port: PGPORT
    });

    this.pgClient.on('error', () => {
      logger.error('Database connection lost!')
    });

    // Create initial table
    this.pgClient.on('connect', (client) => {
      client.query('CREATE TABLE IF NOT EXISTS person (id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, userId int UNIQUE, name VARCHAR UNIQUE)')
        .catch((err) => logger.error('Failed to create table', err))
    });
  }

  async insert(userId, name) {
    try {
      await this.pgClient.query('INSERT INTO person(userId, name) VALUES($1, $2) ON CONFLICT DO NOTHING', [userId, name]);
    } catch (err) {
      logger.info(`Failed to insert ${userId}, ${name}`, err);
      throw err
    }
  }
}

module.exports = new DatabaseService();
