apiVersion: v1
kind: Service
metadata:
  name: person-server-service
spec:
  type: ClusterIP
  selector:
    component: person-server
  ports:
    - port: {{ .Values.person_server.port }}
      targetPort: {{ .Values.person_server.port }}
