apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # the volume can be mounted as a read-write by a single node.
  resources:
    requests:
      storage: 2Gi
